# Configuración principal de Scientific Article Aggregator

# Temas de interés para la búsqueda de artículos
topics:
  - "bioinformática"
  - "programación en biología"
  - "análisis de datos biológicos"
  - "interacción planta-microorganismos"
  - "educación científica"
  - "investigación en divulgación de la ciencia"
  - "computational biology"
  - "plant-microbe interactions"
  - "scientific education"
  - "science communication"

# Configuración de búsqueda
search:
  max_articles_per_source: 50
  date_range_days: 7  # Buscar artículos de los últimos N días
  languages: ["en", "es"]  # Idiomas preferidos
  
# Configuración de procesamiento de texto
text_processing:
  max_summary_length: 300  # Palabras máximas en resúmenes
  max_post_length: 1500    # Palabras máximas en posts
  remove_technical_jargon: true
  casual_tone: true
  
# Configuración del Knowledge Graph
knowledge_graph:
  max_entities: 100
  min_entity_frequency: 2
  include_authors: true
  include_institutions: true
  include_concepts: true
  
# Configuración de la base de datos
database:
  path: "data/articles.db"
  backup_frequency: "daily"
  
# Configuración de salida
output:
  markdown_dir: "outputs/posts"
  create_daily_summary: true
  include_metadata: true
  
# Configuración del programador
scheduler:
  daily_run_time: "08:00"  # Hora de ejecución diaria (formato 24h)
  timezone: "America/Mexico_City"
  retry_attempts: 3
  
# Configuración de la interfaz Streamlit
streamlit:
  page_title: "Scientific Article Aggregator"
  page_icon: "🔬"
  layout: "wide"
  sidebar_state: "expanded"
  
# Configuración de logging
logging:
  level: "INFO"
  file: "logs/app.log"
  max_file_size: "10MB"
  backup_count: 5

